// Regenerates the card dataset from the raw clash.ninja markup kept in supbase.md.
// Outputs: src/lib/cards.mjs (server) and public/data/cards.json (browser).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const CATEGORIES = {
  0: 'Elixir Troops',
  1: 'Dark Elixir Troops',
  2: 'Super Troops',
  3: 'Builder Base Troops',
};

const html = readFileSync(resolve(root, 'supbase.md'), 'utf8');
const re = /data-card-number="(\d+)" data-entity-id="(\d+)" data-type-id="(\d+)" title="([^"]+)"/g;

const seen = new Set();
const cards = [];
for (const [, number, entity, type, name] of html.matchAll(re)) {
  const id = Number(number);
  if (seen.has(id)) continue;
  seen.add(id);
  cards.push({ id, entity: Number(entity), category: Number(type), name });
}
cards.sort((a, b) => a.id - b.id);

if (cards.length !== 60) throw new Error(`Expected 60 cards, parsed ${cards.length}`);

const payload = {
  categories: CATEGORIES,
  cards: cards.map((c) => ({ ...c, icon: `/cards/${c.entity}.png` })),
};

mkdirSync(resolve(root, 'public/data'), { recursive: true });
writeFileSync(resolve(root, 'public/data/cards.json'), JSON.stringify(payload, null, 2) + '\n');

writeFileSync(
  resolve(root, 'src/lib/cards.mjs'),
  `// Generated by scripts/gen-cards.mjs — do not edit by hand.\n` +
    `export const CATEGORIES = ${JSON.stringify(CATEGORIES, null, 2)};\n\n` +
    `export const CARDS = ${JSON.stringify(payload.cards, null, 2)};\n\n` +
    `export const CARD_IDS = new Set(CARDS.map((c) => c.id));\n` +
    `export const CARD_BY_ID = new Map(CARDS.map((c) => [c.id, c]));\n`,
);

console.log(`Wrote ${cards.length} cards.`);
